//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiestas.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fiestas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11780392_globos_para_cumpleaños_o_una_tarjeta_del_partido {
            get {
                object obj = ResourceManager.GetObject("11780392-globos-para-cumpleaños-o-una-tarjeta-del-partido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1462235eb16a207fbe59b53e4682af0a {
            get {
                object obj = ResourceManager.GetObject("1462235eb16a207fbe59b53e4682af0a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1476012327 {
            get {
                object obj = ResourceManager.GetObject("1476012327", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2311452340 {
            get {
                object obj = ResourceManager.GetObject("2311452340", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _26b9c27fa9b0debf2b56d1a27ebedf58 {
            get {
                object obj = ResourceManager.GetObject("26b9c27fa9b0debf2b56d1a27ebedf58", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3f4b5de1e6ac0893a90abfbb49ee3863 {
            get {
                object obj = ResourceManager.GetObject("3f4b5de1e6ac0893a90abfbb49ee3863", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _415eZwjq9IL {
            get {
                object obj = ResourceManager.GetObject("415eZwjq9IL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _77240085_rosa_púrpura_cumpleaños_de_fondo_con_globos_y_brillante {
            get {
                object obj = ResourceManager.GetObject("77240085-rosa-púrpura-cumpleaños-de-fondo-con-globos-y-brillante", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _77240085_rosa_púrpura_cumpleaños_de_fondo_con_globos_y_brillante1 {
            get {
                object obj = ResourceManager.GetObject("77240085-rosa-púrpura-cumpleaños-de-fondo-con-globos-y-brillante1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7Irz5 {
            get {
                object obj = ResourceManager.GetObject("7Irz5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8_bases_de_pastel_boda_fiesta_cumpleanos_platinumcakeware_D_NQ_NP_640565_MLM29205018583_012019_Q {
            get {
                object obj = ResourceManager.GetObject("8-bases-de-pastel-boda-fiesta-cumpleanos-platinumcakeware-D_NQ_NP_640565-MLM29205" +
                        "018583_012019-Q", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _80db921ea4916df0d2a6d9a46fe30cdc {
            get {
                object obj = ResourceManager.GetObject("80db921ea4916df0d2a6d9a46fe30cdc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _81KMYsw7uBL__SL1500_ {
            get {
                object obj = ResourceManager.GetObject("81KMYsw7uBL._SL1500_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _96125365_collection_of_pink_birthday_party_objects_in_a_gift_box {
            get {
                object obj = ResourceManager.GetObject("96125365-collection-of-pink-birthday-party-objects-in-a-gift-box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9daa5318_b9ee_411c_b600_3efeb45c5b69 {
            get {
                object obj = ResourceManager.GetObject("9daa5318-b9ee-411c-b600-3efeb45c5b69", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9daa5318_b9ee_411c_b600_3efeb45c5b691 {
            get {
                object obj = ResourceManager.GetObject("9daa5318-b9ee-411c-b600-3efeb45c5b691", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9daa5318_b9ee_411c_b600_3efeb45c5b692 {
            get {
                object obj = ResourceManager.GetObject("9daa5318-b9ee-411c-b600-3efeb45c5b692", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9daa5318_b9ee_411c_b600_3efeb45c5b693 {
            get {
                object obj = ResourceManager.GetObject("9daa5318-b9ee-411c-b600-3efeb45c5b693", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9f648ce8c557afabf750be68e1802439 {
            get {
                object obj = ResourceManager.GetObject("9f648ce8c557afabf750be68e1802439", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a00db3418d3322c8cdf9292fa6f80841 {
            get {
                object obj = ResourceManager.GetObject("a00db3418d3322c8cdf9292fa6f80841", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A010405_010405 {
            get {
                object obj = ResourceManager.GetObject("A010405_010405", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alquilar_Disco_Movil_4000 {
            get {
                object obj = ResourceManager.GetObject("Alquilar-Disco-Movil-4000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alquilar_sonido_y_luz_party {
            get {
                object obj = ResourceManager.GetObject("Alquilar-sonido-y-luz-party", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arreglos_florales_para_una_fiesta_de_16_anos {
            get {
                object obj = ResourceManager.GetObject("arreglos-florales-para-una-fiesta-de-16-anos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap birthday_celebration_background_birthday_balloon_wallpaper_vector {
            get {
                object obj = ResourceManager.GetObject("birthday-celebration-background-birthday-balloon-wallpaper-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap birthday_celebration_background_birthday_balloon_wallpaper_vector1 {
            get {
                object obj = ResourceManager.GetObject("birthday-celebration-background-birthday-balloon-wallpaper-vector1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BRLioKNCEAAyoCf {
            get {
                object obj = ResourceManager.GetObject("BRLioKNCEAAyoCf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cfb_206105 {
            get {
                object obj = ResourceManager.GetObject("cfb_206105", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comidas_sanas_menu_saludable_boda_original_ideas {
            get {
                object obj = ResourceManager.GetObject("comidas-sanas-menu-saludable-boda-original-ideas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap confeti_dorado_sobre_fondo_negro_45843_282 {
            get {
                object obj = ResourceManager.GetObject("confeti-dorado-sobre-fondo-negro_45843-282", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Consejos_menú_boda_optimizada_2 {
            get {
                object obj = ResourceManager.GetObject("Consejos-menú-boda-optimizada-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e555250b66dac6077e5719e3b192444e {
            get {
                object obj = ResourceManager.GetObject("e555250b66dac6077e5719e3b192444e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fiesta_0 {
            get {
                object obj = ResourceManager.GetObject("fiesta_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fiesta_hawaiana {
            get {
                object obj = ResourceManager.GetObject("fiesta-hawaiana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fiestas {
            get {
                object obj = ResourceManager.GetObject("fiestas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fiestas1 {
            get {
                object obj = ResourceManager.GetObject("fiestas1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imagenes_de_arreglos_florales_para_fiestas_5 {
            get {
                object obj = ResourceManager.GetObject("imagenes-de-arreglos-florales-para-fiestas-5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images1 {
            get {
                object obj = ResourceManager.GetObject("images1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_5002_1 {
            get {
                object obj = ResourceManager.GetObject("IMG_5002-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_5038_1 {
            get {
                object obj = ResourceManager.GetObject("IMG_5038-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mantel_rojo_casaymantel_ideas_decoracion_mesa_mantelerias {
            get {
                object obj = ResourceManager.GetObject("mantel-rojo-casaymantel-ideas-decoracion-mesa-mantelerias", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NOZZEcentrotavola_2_435x288 {
            get {
                object obj = ResourceManager.GetObject("NOZZEcentrotavola-2-435x288", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tela_rico_confeti_fondo_blanco_jersey_por_10_cm_bajo_medida_l {
            get {
                object obj = ResourceManager.GetObject("tela-rico-confeti-fondo-blanco-jersey-por-10-cm-bajo-medida-l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tela_rico_confeti_fondo_blanco_jersey_por_10_cm_bajo_medida_l1 {
            get {
                object obj = ResourceManager.GetObject("tela-rico-confeti-fondo-blanco-jersey-por-10-cm-bajo-medida-l1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumb2_happy_birthday_bengal_lights_cake_birthday_cake_cupcake {
            get {
                object obj = ResourceManager.GetObject("thumb2-happy-birthday-bengal-lights-cake-birthday-cake-cupcake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap torta_chanel_compressor {
            get {
                object obj = ResourceManager.GetObject("torta-chanel-compressor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
